### ISSUE TITLE
A new time vote doesn't always show up when refreshing the page

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb#1035]
When I add a new time vote and refresh the page, it seems like sometimes the page doesn't update to show the correct number of votes. Is this a caching issue? Is there anything we should do about it?

**Comment by dfabulich** [comment]
I believe the issue is that the time votes section only appears when there's at least 1 rating or at least 1 written review.

In the local dev DB, the newest game is "REPEAT IT BACK TO ME" and it has no ratings/reviews.

* If you submit a time vote for it, you won't see it above the descirption; it just says, "No reviews yet."
* If you submit a rating, it says:
    > ★★★★★ (based on 1 rating)
    > Estimated play time: 3 hours (based on 1 vote)
    > No reviews yet
* If you remove the rating, the "Estimated play time" disappears.
* If you write a review with no star rating, it says:
    > Estimated play time: 3 hours (based on 1 vote)
    > 1 review
* If you delete the review, the "Esttimated play time" disappears again.

**Comment by alice-blue** [comment]
I think the whole section to display the time is (unintentionally) inside of an "else" clause in the rating/review section.

**Comment by dfabulich** [comment]
I'm fixing it
