### ISSUE TITLE
Searches should be able to sort by estimated play time

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#1051]
You should be able to sort by median estimated play time.

**Comment by dfabulich** [comment]
Most games won't have any time votes. What should sort do in that case to break the tie? (Null first? Null last? Should the nulls be in _any_ order?)

**Comment by alice-blue** [comment]
If someone is choosing to sort by estimated play time, I'm guessing because it's important to them how long a game is. If we show the unknown-time games first, then to get to the games that we actually know the time for, users would have to go to the very end of the search results. I can't see how it would be helpful to show the unknown-time games first unless someone is specifically looking for games with no times (because they want to help add times to games with no times).

**Comment by dfabulich** [comment]
Would we put null last when sorting longest first _and_ when sorting shortest first? (And, in what order should the nulls appear?)

**Comment by alice-blue** [comment]
I guess the nulls would appear in order of relevance to whatever the search terms were.

My inclination would be to put them at the end in both directions, yes--otherwise it seems like they'd get in the way of what the person was looking for.

But maybe there's a better solution.
